return {
  {
    "williamboman/mason-lspconfig.nvim",
    dependencies = { "williamboman/mason.nvim", "williamboman/mason-lspconfig.nvim" },
    opts = {
      ensure_installed = {
        "bashls",
        "cssls",
        "cssmodules_ls",
        "dockerls",
        "docker_compose_language_service",
        "dotls",
        "eslint",
        "emmet_ls",
        "graphql",
        "html",
        "jsonls",
        "lua_ls",
        "marksman",
        "intelephense",
        "puppet",
        "sqlls",
        "sqls",
        "tailwindcss",
        "tsserver",
        "volar",
      },
      automatic_installation = true,
    },
  },
}
